name: stuntguard
description: Mobile-Based Stunting Detection System Using Machine Learning and WHO Growth Standards

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  sqflite: ^2.0.0
  path_provider: ^2.0.0
  riverpod: ^2.0.0
  fl_chart: ^0.66.0
  http: ^1.0.0
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700